CREATE TABLE IF NOT EXISTS Genre (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistGenre (
	ArtistID INTEGER NOT NULL REFERENCES Artists(ID),
	GenreID INTEGER NOT NULL REFERENCES Genre(ID)
);

CREATE TABLE IF NOT EXISTS Albums (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(80) NOT NULL,
	Releaseyear INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistAlbum (
	ArtistID INTEGER NOT NULL REFERENCES Artists(ID),
	AlbumID INTEGER NOT NULL REFERENCES Albums(ID),
);

CREATE TABLE IF NOT EXISTS Songs (
	ID SERIAL PRIMARY KEY,
	Album INTEGER NOT NULL REFERENCES Albums(ID),
	Name VARCHAR(80) NOT NULL,
	Length TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Compilations (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	ReleaseYear INTEGER NOT NULL 
);

CREATE TABLE IF NOT EXISTS CompilationSong (
	CompilationID INTEGER NOT NULL REFERENCES Compilations(ID),
	SongID INTEGER NOT NULL REFERENCES Songs(ID) 
);